In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path  
from collections import deque
from itertools import islice
from enum import Enum

In [2]:
gyro_meas1 = (1, 2, 3)
gyro_meas2 = (4, 5, 6)

time1 = 0
time2 = 1
# print([gyro_meas1, gyro_meas2])
# print(list(zip(gyro_meas1, gyro_meas2)))
gyro_buf = []
gyro_buf.append((gyro_meas1, time1))
gyro_buf.append((gyro_meas2, time2))

print(gyro_buf)
print(list(zip(*gyro_buf)))

[((1, 2, 3), 0), ((4, 5, 6), 1)]
[((1, 2, 3), (4, 5, 6)), (0, 1)]


In [3]:
np_arr = np.zeros(shape=(5,4), dtype=np.int8)
np_arr[0] = *gyro_meas1, time1
np_arr[1] = *gyro_meas2, time2
print(np_arr)
print(np_arr[:, 1])
for ind, name in enumerate(["x", "y", "z"]):
       print(f"name {name} | index: {ind}: {np_arr[:, 3]} , {np_arr[:, ind]}")


[[1 2 3 0]
 [4 5 6 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[2 5 0 0 0]
name x | index: 0: [0 1 0 0 0] , [1 4 0 0 0]
name y | index: 1: [0 1 0 0 0] , [2 5 0 0 0]
name z | index: 2: [0 1 0 0 0] , [3 6 0 0 0]


In [11]:
bias_example = np.array([[ 9.11979418-0.j],
            [ 8.16589624-0.j],
            [23.49661059-0.j]])
bias_example.shape
np_arr[:, 0:3] - bias_example.T

array([[ -8.11979418+0.j,  -6.16589624+0.j, -20.49661059+0.j],
       [ -5.11979418+0.j,  -3.16589624+0.j, -17.49661059+0.j],
       [ -9.11979418+0.j,  -8.16589624+0.j, -23.49661059+0.j],
       [ -9.11979418+0.j,  -8.16589624+0.j, -23.49661059+0.j],
       [ -9.11979418+0.j,  -8.16589624+0.j, -23.49661059+0.j]])

In [8]:
np.max(np_arr)

np.int8(6)

In [ ]:
def get_slice_zero(data: np.ndarray):
    print(data[:, 0])


[2 5 0 0 0]


In [ ]:
np_common = np.zeros(shape = (10, 4))
meas = deque()
records  = meas.extend([[1,2,3, 50.0], [1,2,3, 50.0], [1,2,3, 50.0], [1,2,3, 50.0], [1,2,3, 50.0]])
last_ind = 0
meas_cnt = 5
np_common[last_ind:meas_cnt, :] = list(islice(meas,last_ind,meas_cnt))
print(np_common)

In [ ]:
meas_buffer = deque(maxlen=5)
new_gyro_data = (1.0, 2., 3.0)
time = 10.0
for i in range(6):
    meas_buffer.append((*new_gyro_data, time*(i+1)))
print(meas_buffer)
gyro_arr = np.array(meas_buffer)
print(gyro_arr)
for ind in range(0, 3):
    print(f"Time: {gyro_arr[:, 3]}, meas: {gyro_arr[:, ind]}") 
# meas_buffer.append((*resp.accel_mes,  resp.timestamp / 1000.0))

3d figures

In [22]:
# fig = plt.figure()
# ax = fig.add_subplot(projection='3d')
theta = np.linspace(0, 9, 10)
phi = np.linspace(0, 9, 10)
phi, theta = np.meshgrid(phi, theta)
# print(type(phi), type(theta))
print(theta[:5,:5])
phi[:5,:5]

# Radius = 1
# xs = Radius * np.sin(phi) * np.cos(theta)
# ys = Radius * np.sin(phi) * np.sin(theta)
# zs = Radius * np.cos(phi)
# ax.scatter(xs, ys, zs)

# ax.set_xlabel('X Label')
# ax.set_ylabel('Y Label')
# ax.set_zlabel('Z Label')

# plt.show()

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [6]:
filename = Path("log_data")/"imu_log_2026-08-28_02-23-12.csv"
print(filename)
# get rid of spaces in header of origin .csv 
new_header =  ["time_ms", 
               "acc_x", "acc_y", "acc_z", 
               "gyro_x", "gyro_y", "gyro_z", 
               "mag_x", "mag_y", "mag_z"]
df = pd.read_csv(filename,
                header=0,
                names=new_header)
print(df.shape)
df.head(5)

log_data\imu_log_2026-08-28_02-23-12.csv
(1636, 10)


,time_ms,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,mag_x,mag_y,mag_z
0,75975,-0.197,-0.022,1.013,1.328,1.374,-0.183,-27.60,22.05,32.25
1,75995,-0.195,-0.023,1.018,1.405,1.496,-0.275,-28.50,23.25,32.10
2,76015,-0.200,-0.022,1.016,1.420,1.466,-0.290,-26.85,22.05,31.20
3,76035,-0.198,-0.019,1.017,1.282,1.282,-0.321,-28.95,22.35,32.25
4,76055,-0.196,-0.021,1.014,1.282,1.374,-0.137,-28.20,22.35,32.25


In [7]:
mag_df = df.loc[:,["mag_x", "mag_y", "mag_z"]]
mag_df.head()
filename = Path("log_data") / "imu_log_2026-08-28_02-23-12_mag.csv"
mag_df.to_csv(path_or_buf=filename, mode = 'w', index = False, header=False)